swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "KidsHaru - 아동 사진 공유 서비스"
  termsOfService: ""
  contact:
    email: "embrapers263@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "api.kidsharu.com"
basePath: "/v1"


tags:
- name: "auth"
  description: "로그인과 회원가입"
- name: "teacher"
  description: "Operations about teacher"


paths:

  /users/teachers:
    post:
      tags:
      - "auth"
      summary: "교사 회원가입"
      parameters: 
      - name: "body"
        in: "body"
        required: true
        schema:
          type: object
          properties:
            id:
              $ref: "#/definitions-parameters/id"
            password:
              $ref: "#/definitions-parameters/password"
            name:
              type: string
              example: "홍길동"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/LoginResult"
        400:
          $ref: "#/definitions-response/InsufficientParameters"
        409:
          $ref: "#/definitions-response/AlreadyExistID"
        500:
          $ref: "#/definitions-response/InternalServerError"

  /users/parents:
    post:
      tags:
      - "auth"
      summary: "학부모 회원가입"
      parameters: 
      - name: "body"
        in: "body"
        required: true
        schema:
          type: object
          properties:
            id:
              $ref: "#/definitions-parameters/id"
            password:
              $ref: "#/definitions-parameters/password"
            invite_code:
              type: string
              example: "q1w2e3"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/LoginResult"
        400:
          $ref: "#/definitions-response/InsufficientParameters"
        409:
          $ref: "#/definitions-response/AlreadyExistID"
        500:
          $ref: "#/definitions-response/InternalServerError"
          
  /users/teachers/auth:
    post:
      tags:
      - "auth"
      summary: "교사 로그인"
      parameters: 
      - name: "body"
        in: "body"
        required: true
        schema:
          type: object
          properties:
            id:
              $ref: "#/definitions-parameters/id"
            password:
              $ref: "#/definitions-parameters/password"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/LoginResult"
        400:
          $ref: "#/definitions-response/InsufficientParameters"
        404:
          description: "아이디 또는 비밀번호가 틀렸을 경우"
          schema:
            type: object
            properties:
              msg:
                type: string
                example: "Invalid password"
        500:
          $ref: "#/definitions-response/InternalServerError"
          
  /users/parents/auth:
    post:
      tags:
      - "auth"
      summary: "학부모 로그인"
      parameters: 
      - name: "body"
        in: "body"
        required: true
        schema:
          type: object
          properties:
            id:
              $ref: "#/definitions-parameters/id"
            password:
              $ref: "#/definitions-parameters/password"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/LoginResult"
        400:
          $ref: "#/definitions-response/InsufficientParameters"
        404:
          description: "아이디 또는 비밀번호가 틀렸을 경우"
          schema:
            type: object
            properties:
              msg:
                type: string
                example: "Invalid password"
        500:
          $ref: "#/definitions-response/InternalServerError"
          
  /teachers/children:
    get:
      tags:
      - "teacher"
      summary: "교사의 원아 리스트"
      parameters: []
      responses:
        200:
          description: "Success"
          schema:
            type: array
            items:
              $ref: "#/definitions/Child"
        400:
          $ref: "#/definitions-response/InsufficientParameters"
        500:
          $ref: "#/definitions-response/InternalServerError"
    post:
      tags:
      - "teacher"
      summary: "교사의 원아 추가"
      parameters: 
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/ChildWithoutId"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Child"
        400:
          $ref: "#/definitions-response/InsufficientParameters"
        409:
          $ref: "#/definitions-response/AlreadyExist"
        500:
          $ref: "#/definitions-response/InternalServerError"
          
  /teachers/children/{child_id}:
    get:
      tags:
      - "teacher"
      summary: "교사의 원아 정보"
      parameters: 
      - $ref: "#/definitions-parameters/ChildId"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Child"
        400:
          $ref: "#/definitions-response/InsufficientParameters"
        404:
          $ref: "#/definitions-response/NotExists"
        500:
          $ref: "#/definitions-response/InternalServerError"
    put:
      tags:
      - "teacher"
      summary: "교사의 원아 삭제"
      parameters: 
      - $ref: "#/definitions-parameters/ChildId"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/ChildWithoutId"
      responses:
        204:
          description: "Success"
        400:
          $ref: "#/definitions-response/InsufficientParameters"
        404:
          $ref: "#/definitions-response/NotExists"
        500:
          $ref: "#/definitions-response/InternalServerError"
    delete:
      tags:
      - "teacher"
      summary: "교사의 원아 삭제"
      parameters: 
      - $ref: "#/definitions-parameters/ChildId"
      responses:
        204:
          description: "Success"
        400:
          $ref: "#/definitions-response/InsufficientParameters"
        404:
          $ref: "#/definitions-response/NotExists"
        500:
          $ref: "#/definitions-response/InternalServerError"


definitions-parameters:
  id:
    type: string
    example: "example"
  password:
    type: string
    example: "03AC674216F3E15C761EE1A5E255F067953623C8B388B4459E13F978D7C846F4"
    description: "SHA256 Hashed Password"
  
  ChildId:
    name: "child_id"
    in: "path"
    description: "삭제하려는 원아의 child_id"
    required: true
    type: integer


definitions-response:
  InternalServerError:
    description: "예상치 못한 서버 에러가 발생한 경우"
    schema:
      type: object
      properties:
        msg:
          type: string
          example: "~~"
  InsufficientParameters:
    description: "클라이언트에서 보내준 데이터에서 빠진 부분이 있는 경우"
    schema:
      type: object
      properties:
        msg:
          type: string
          example: "There is no [field name]"
  AlreadyExistID:
    description: "이미 존재하는 아이디로 회원가입 하려는 경우"
    schema:
      type: object
      properties:
        msg:
          type: string
          example: "Already Exist ID"
  AlreadyExist:
    description: "이미 존재하는 경우"
    schema:
      type: object
      properties:
        msg:
          type: string
          example: "Already Exist"
  NotExists:
    description: "존재 하지 않는 경우"
    schema:
      type: object
      properties:
        msg:
          type: string
          example: "Not Exists"


definitions:
  LoginResult:
    type: object
    properties:
      access_token:
        type: string
        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
      is_teacher:
        type: "boolean"
        example: true
  Child:
    type: object
    properties:
      child_id:
        type: integer
        example: 1
      name:
        type: string
        example: "박철수"
      contact:
        type: string
        example: "010-1234-1234"
  ChildWithoutId:
    type: object
    properties:
      name:
        type: string
        example: "박철수"
      contact:
        type: string
        example: "010-1234-1234"